"""add magic tokens

Revision ID: fbb06786ffab
Revises: f367e683ca60
Create Date: 2026-05-29 13:50:08.025671
"""
from alembic import op
import sqlalchemy as sa


revision = 'fbb06786ffab'
down_revision = 'f367e683ca60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
